version: '3.8'
services:
  postgres:
    networks:
      - backend
    image: postgres
    container_name: postgres-db
    restart: on-failure
    environment:
      POSTGRES_USER: run/secrets/db_user
      POSTGRES_PASSWORD: run/secrets/db_password
      POSTGRES_DB: run/secrets/db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    secrets:
      - db
      - db_password
      - db_user

  app:
    networks:
      - backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    image: java_api:v1
    container_name: java-api
    restart: always
    env_file: dockerSecrets/api.env

volumes:
  postgres_data:
secrets:
  db_password:
    file: dockerSecrets/db_password.txt
  db_user:
    file: dockerSecrets/db_user.txt
  db:
    file: dockerSecrets/db.txt
  api_db_url:
    file: dockerSecrets/api.env
networks:
  backend: